/**
 * Populate DB with sample data on server start
 * to disable, edit config/environment/index.js, and set `seedDB: false`
 */

'use strict';
import sqldb from '../sqldb';
import config from './environment/';

export default function seedDatabaseIfNeeded () {
  if (config.seedDB) {
    let Golfer = sqldb.Golfer;
    let User = sqldb.User;

    Golfer.destroy({ where: {} })
      .then(() => {
        let golfers = Golfer.bulkCreate([
          { name: 'Dustin Johnson', espnId: '3448' },
          { name: 'Jordan Spieth', espnId: '5467' },
          { name: 'Rickie Fowler', espnId: '3702' },
          { name: 'Jon Rahm', espnId: '9780' },
          { name: 'Sergio Garcia', espnId: '158' },
          { name: 'Justin Rose', espnId: '569' },
          { name: 'Rory McIlroy', espnId: '3470' },
          { name: 'Hideki Matsuyama', espnId: '5860' },
          { name: 'Tommy Fleetwood', espnId: '5539' },
          { name: 'Henrik Stenson', espnId: '576' },
          { name: 'Adam Scott', espnId: '388' },
          { name: 'Brooks Koepka', espnId: '6798' },
          { name: 'Jason Day', espnId: '1680' },
          { name: 'Paul Casey', espnId: '72' },
          { name: 'Alex Noren', espnId: '3832' },
          { name: 'Phil Mickelson', espnId: '308' },
          { name: 'Louis Oosthuizen', espnId: '1293' },
          { name: 'Branden Grace', espnId: '4383' },
          { name: 'Marc Leishman', espnId: '3351' },
          { name: 'Justin Thomas', espnId: '4848' },
          { name: 'Matt Kuchar', espnId: '257' },
          { name: 'Thomas Pieters', espnId: '9031' },
          { name: 'Padraig Harrington', espnId: '186' },
          { name: 'Rafael Cabrera Bello', espnId: '4321' },
          { name: 'Patrick Reed', espnId: '5579' },
          { name: 'Shane Lowry', espnId: '4587' },
          { name: 'Charl Schwartzel', espnId: '1097' },
          { name: 'Brandt Snedeker', espnId: '' },
          { name: 'Ian Poulter', espnId: '619' },
          { name: 'Lee Westwood', espnId: '455' },
          { name: 'Daniel Berger', espnId: '9025' },
          { name: 'Matthew Fitzpatrick', espnId: '9037' },
          { name: 'Andy Sullivan', espnId: '5956' },
          { name: 'Ross Fisher', espnId: '3462' },
          { name: 'Zach Johnson', espnId: '686' },
          { name: 'Martin Kaymer', espnId: '3670' },
          { name: 'Francesco Molinari', espnId: '1483' },
          { name: 'Tyrrell Hatton', espnId: '5553' },
          { name: 'Bernd Wiesberger', espnId: '4317' },
          { name: 'Chris Wood', espnId: '3839' },
          { name: 'Steve Stricker', espnId: '412' },
          { name: 'Kevin Kisner', espnId: '2552' },
          { name: 'Bill Haas', espnId: '774' },
          { name: 'Brian Harman', espnId: '1225' },
          { name: 'J.B. Holmes', espnId: '1067' },
          { name: 'Jason Dufner', espnId: '110' },
          { name: 'Soren Kjeldsen', espnId: '547' },
          { name: 'Bryson DeChambeau', espnId: '10046' },
          { name: 'Byeong Hun An', espnId: '5285' },
          { name: 'Charley Hoffman', espnId: '205' },
          { name: 'Peter Uihlein', espnId: '1674' },
          { name: 'Russell Henley', espnId: '5409' },
          { name: 'Thorbjorn Olesen', espnId: '5140' },
          { name: 'Tony Finau', espnId: '2230' },
          { name: 'Andrew Johnston', espnId: '5838' },
          { name: 'Bubba Watson', espnId: '780' },
          { name: 'Ryan Fox', espnId: '4251' },
          { name: 'Brendan Steele', espnId: '3596' },
          { name: 'Emiliano Grillo', espnId: '5882' },
          { name: 'Hideto Tanihara', espnId: '1099' },
          { name: 'Jimmy Walker', espnId: '446' },
          { name: 'Kevin Chappell', espnId: '3857' },
          { name: 'Kyle Stanley', espnId: '1778' },
          { name: 'Si Woo Kim', espnId: '7081' },
          { name: 'Charles Howell III', espnId: '208' },
          { name: 'Martin Laird', espnId: '2571' },
          { name: 'Webb Simpson', espnId: '1614' },
          { name: 'Billy Horschel', espnId: '1651' },
          { name: 'Xander Schauffele', espnId: '10140' },
          { name: 'Adam Hadwin', espnId: '5548' },
          { name: 'Richie Ramsay', espnId: '1782' },
          { name: 'Russell Knox', espnId: '4483' },
          { name: 'Joost Luiten', espnId: '4831' },
          { name: 'Anirban Lahiri', espnId: '4989' },
          { name: 'Gary Woodland', espnId: '3550' },
          { name: 'Alexander Levy', espnId: '6041' },
          { name: 'Callum Shinkwin', espnId: '9258' },
          { name: 'Cameron Smith', espnId: '9131' },
          { name: 'Jamie Lovemark', espnId: '1676' },
          { name: 'Matthew Southgate', espnId: '5852' },
          { name: 'Pat Perez', espnId: '707' },
          { name: 'Ryan Moore', espnId: '809' },
          { name: 'Stewart Cink', espnId: '78' },
          { name: 'Wesley Bryan', espnId: '10360' },
          { name: 'Pablo Larrazabal', espnId: '3829' },
          { name: 'Robert Streb', espnId: '5619' },
          { name: 'Sean O\'Hair', espnId: '1359' },
          { name: 'Danny Willett', espnId: '4304' },
          { name: 'Haotong Li', espnId: '5934' },
          { name: 'William McGirt', espnId: '3532' },
          { name: 'Dylan Frittelli', espnId: '5167' },
          { name: 'Ernie Els', espnId: '123' },
          { name: 'Fabrizio Zanotti', espnId: '1770' },
          { name: 'Kevin Na', espnId: '318' },
          { name: 'Brandon Stone', espnId: '6280' },
          { name: 'Alexander Bjork', espnId: '9469' },
          { name: 'Andrew Dodt', espnId: '3639' },
          { name: 'David Horsey', espnId: '3825' },
          { name: 'Sung-hoon Kang', espnId: '4449' },
          { name: 'Thongchai Jaidee', espnId: '222' },
          { name: 'Paul Waring', espnId: '3474' },
          { name: 'Julian Suri', espnId: '10195' },
          { name: 'David Drysdale', espnId: '1453' },
          { name: 'David Lipsky', espnId: '6701' },
          { name: 'Matthieu Pavon', espnId: '10596' },
          { name: 'Richard Bland', espnId: '1441' },
          { name: 'Scott Hend', espnId: '1178' },
          { name: 'Jeunghun Wang', espnId: '9754' },
          { name: 'Jhonattan Vegas', espnId: '1030' },
          { name: 'Michael Lorenzo-Vera', espnId: '4272' },
          { name: 'Roberto Castro', espnId: '3740' },
          { name: 'Aaron Baddeley', espnId: '16' },
          { name: 'Kyung-tae Kim', espnId: '8858' },
          { name: 'Maverick McNealy', espnId: '9530' },
          { name: 'Yusaku Miyazato', espnId: '978' },
          { name: 'Paul Lawrie', espnId: '265' },
          { name: 'Sebastian Munoz', espnId: '10404' },
          { name: 'Shiv Kapur', espnId: '1583' },
          { name: 'Austin Connelly', espnId: '10017' },
          { name: 'Jbe\' Kruger', espnId: '4993' },
          { name: 'Phachara Khongwatmai', espnId: '9852' },
          { name: 'Prayad Marksaeng', espnId: '3687' },
          { name: 'Young-han Song', espnId: '10422' },
          { name: 'Yuta Ikeda', espnId: '4712' },
          { name: 'Darren Fichardt', espnId: '868' },
          { name: 'Mark Foster', espnId: '1087' },
          { name: 'Mike Hendry', espnId: '4252' },
          { name: 'Yi Keun Chang', espnId: '11175' },
          { name: 'Tom Lehman', espnId: '268' },
          { name: 'Adam Bland', espnId: '1688' },
          { name: 'Alfie Plant', espnId: '11177' },
          { name: 'Ashley Hall', espnId: '11176' },
          { name: 'Chan Kim', espnId: '5724' },
          { name: 'Connor Syme', espnId: '10983' },
          { name: 'Gi-Whan Kim', espnId: '6706' },
          { name: 'Harry Ellis', espnId: '11174' },
          { name: 'Haydn McCullen', espnId: '11148' },
          { name: 'John Daly', espnId: '97' },
          { name: 'Kent Bulle', espnId: '6180' },
          { name: 'Luca Cianchetti', espnId: '10227' },
          { name: 'Matthew Griffin', espnId: '4219' },
          { name: 'Paul Broadhurst', espnId: '1280' },
          { name: 'Robert Dinwiddie', espnId: '1797' },
          { name: 'Shaun Norris', espnId: '5057' },
          { name: 'Toby Tree', espnId: '9821' },
          { name: 'Darren Clarke', espnId: '82' },
          { name: 'Joseph Dean', espnId: '6970' },
          { name: 'Laurie Canter', espnId: '5550' },
          { name: 'David Duval', espnId: '115' },
          { name: 'Adam Hodkinson', espnId: '11147' },
          { name: 'Mark O\'Meara', espnId: '325' },
          { name: 'Ryan McCarthy', espnId: '7026' },
          { name: 'Nick McCarthy', espnId: '5827' },
          { name: 'Sandy Lyle', espnId: '281' },
          { name: 'Todd Hamilton', espnId: '1090' }]);
        
        return golfers;
      })
      .then(() => console.log('finished populating golfers'))
      .catch(err => console.log('error populating golfers', err));

    return User.destroy({ where: {} })
      .then(() => User.bulkCreate([{
        provider: 'local',
        name: 'Test User',
        email: 'test@example.com',
        password: 'test'
      }, {
        provider: 'local',
        role: 'admin',
        name: 'Admin',
        email: 'admin@example.com',
        password: 'admin'
      }])
        .then(() => console.log('finished populating users'))
        .catch(err => console.log('error populating users', err)));
  }
}
