const tourneyTitle = '2018 Masters';

const tourneyId = '401025221';

const golferData = [
    { id: 1, name: 'Rory McIlroy', espnId: '', tier: 'A' },
    { id: 2, name: 'Jordan Spieth', espnId: '', tier: 'A' },
    { id: 3, name: 'Justin Thomas', espnId: '', tier: 'A' },
    { id: 4, name: 'Dustin Johnson', espnId: '', tier: 'A' },
    { id: 5, name: 'Tiger Woods', espnId: '', tier: 'A' },
    { id: 6, name: 'Bubba Watson', espnId: '', tier: 'A' },
    { id: 7, name: 'Justin Rose', espnId: '', tier: 'A' },
    { id: 8, name: 'Jason Day', espnId: '', tier: 'A' },
    { id: 9, name: 'Phil Mickelson', espnId: '', tier: 'A' },
    { id: 10, name: 'Rickie Fowler', espnId: '', tier: 'A' },

    { id: 11, name: 'Jon Rahm', espnId: '', tier: 'B' },
    { id: 12, name: 'Paul Casey', espnId: '', tier: 'B' },
    { id: 13, name: 'Sergio Garcia', espnId: '', tier: 'B' },
    { id: 14, name: 'Hideki Matsuyama', espnId: '', tier: 'B' },
    { id: 15, name: 'Alex Noren', espnId: '', tier: 'B' },
    { id: 16, name: 'Henrik Stenson', espnId: '', tier: 'B' },
    { id: 17, name: 'Matt Kuchar', espnId: '', tier: 'B' },
    { id: 18, name: 'Patrick Reed', espnId: '', tier: 'B' },
    { id: 19, name: 'Tommy Fleetwood', espnId: '', tier: 'B' },
    { id: 20, name: 'Adam Scott', espnId: '', tier: 'B' },
    { id: 21, name: 'Ian Poulter', espnId: '', tier: 'B' },
    { id: 22, name: 'Louis Oosthuizen', espnId: '', tier: 'B' },
    { id: 23, name: 'Marc Leishman', espnId: '', tier: 'B' },
    { id: 24, name: 'Bryson DeChambeau', espnId: '', tier: 'B' },
    { id: 25, name: 'Thomas Pieters', espnId: '', tier: 'B' },
    { id: 26, name: 'Tyrrell Hatton', espnId: '', tier: 'B' },

    { id: 27, name: 'Branden Grace', espnId: '', tier: 'C' },
    { id: 28, name: 'Brian Harman', espnId: '', tier: 'C' },
    { id: 29, name: 'Charley Hoffman', espnId: '', tier: 'C' },
    { id: 30, name: 'Daniel Berger', espnId: '', tier: 'C' },
    { id: 31, name: 'Patrick Cantlay', espnId: '', tier: 'C' },
    { id: 32, name: 'Rafa Cabrera-Bello', espnId: '', tier: 'C' },
    { id: 33, name: 'Tony Finau', espnId: '', tier: 'C' },
    { id: 34, name: 'Xander Schauffele', espnId: '', tier: 'C' },
    { id: 35, name: 'Cameron Smith', espnId: '', tier: 'C' },
    { id: 36, name: 'Charl Schwartzel', espnId: '', tier: 'C' },
    { id: 37, name: 'Kevin Chappell', espnId: '', tier: 'C' },
    { id: 38, name: 'Kevin Kisner', espnId: '', tier: 'C' },
    { id: 39, name: 'Kiradech Aphibarnrat', espnId: '', tier: 'C' },
    { id: 40, name: 'Matthew Fitzpatrick', espnId: '', tier: 'C' },
    { id: 41, name: 'Ryan Moore', espnId: '', tier: 'C' },
    { id: 42, name: 'Zach Johnson', espnId: '', tier: 'C' },
    { id: 43, name: 'Adam Hadwin', espnId: '', tier: 'C' },
    { id: 44, name: 'Gary Woodland', espnId: '', tier: 'C' },
    { id: 45, name: 'Pat Perez', espnId: '', tier: 'C' },
    { id: 46, name: 'Russell Henley', espnId: '', tier: 'C' },
    { id: 47, name: 'Brendan Steele', espnId: '', tier: 'C' },
    { id: 48, name: 'Francesco Molinari', espnId: '', tier: 'C' },
    { id: 49, name: 'Jason Dufner', espnId: '', tier: 'C' },
    { id: 50, name: 'Jimmy Walker', espnId: '', tier: 'C' },
    { id: 51, name: 'Patton Kizzire', espnId: '', tier: 'C' },
    { id: 52, name: 'Shubhankar Sharma', espnId: '', tier: 'C' },
    { id: 53, name: 'Webb Simpson', espnId: '', tier: 'C' },

    { id: 54, name: 'Dylan Frittelli', espnId: '', tier: 'D' },
    { id: 55, name: 'Hao Tong Li', espnId: '', tier: 'D' },
    { id: 56, name: 'Martin Kaymer', espnId: '', tier: 'D' },
    { id: 57, name: 'Ross Fisher', espnId: '', tier: 'D' },
    { id: 58, name: 'Bernd Wiesberger', espnId: '', tier: 'D' },
    { id: 59, name: 'Chez Reavie', espnId: '', tier: 'D' },
    { id: 60, name: 'Kyle Stanley', espnId: '', tier: 'D' },
    { id: 61, name: 'Austin Cook', espnId: '', tier: 'D' },
    { id: 62, name: 'Billy Horschel', espnId: '', tier: 'D' },
    { id: 63, name: 'Danny Willett', espnId: '', tier: 'D' },
    { id: 64, name: 'Si Woo Kim', espnId: '', tier: 'D' },
    { id: 65, name: 'Angel Cabrera', espnId: '', tier: 'D' },
    { id: 66, name: 'Fred Couples', espnId: '', tier: 'D' },
    { id: 67, name: 'Jhonattan Vegas', espnId: '', tier: 'D' },
    { id: 68, name: 'Wesley Bryan', espnId: '', tier: 'D' },
    { id: 69, name: 'Ted Potter Jr.', espnId: '', tier: 'D' },
    { id: 70, name: 'Bernhard Langer', espnId: '', tier: 'D' },
    { id: 71, name: 'Joaquin Niemann (A)', espnId: '', tier: 'D' },
    { id: 72, name: 'Satoshi Kodaira', espnId: '', tier: 'D' },
    { id: 73, name: 'Vijay Singh', espnId: '', tier: 'D' },
    { id: 74, name: 'Yusaku Miyazato', espnId: '', tier: 'D' },
    { id: 75, name: 'Yuta Ikeda', espnId: '', tier: 'D' },
    { id: 76, name: 'Doc Redman (A)', espnId: '', tier: 'D' },
    { id: 77, name: 'Doug Ghim (A)', espnId: '', tier: 'D' },
    { id: 78, name: 'Harry Ellis (A)', espnId: '', tier: 'D' },
    { id: 79, name: 'Trevor Immelman', espnId: '', tier: 'D' },
    { id: 80, name: 'Yuxin Lin (A)', espnId: '', tier: 'D' },
    { id: 81, name: 'Jose Maria Olazabal', espnId: '', tier: 'D' },
    { id: 82, name: 'Matt Parziale (A)', espnId: '', tier: 'D' },
    { id: 83, name: 'Mike Weir', espnId: '', tier: 'D' },
    { id: 84, name: 'Ian Woosnam', espnId: '', tier: 'D' },
    { id: 85, name: 'Larry Mize', espnId: '', tier: 'D' },
    { id: 86, name: 'Mark O\'Meara', espnId: '', tier: 'D' },
    { id: 87, name: 'Sandy Lyle', espnId: '', tier: 'D' }
];

const contestantData = [
    { id: 1, name: 'Brian Hoffman', entries: [[1, 15, 30, 63], [5, 12, 35, 59], [6, 14, 27, 56]] },
    { id: 2, name: 'Ryan Boudouris', entries: [[1, 17, 34, 57], [5, 12, 29, 59], [7, 16, 29, 56]] },
    { id: 3, name: 'Matt Kavanaugh', entries: [[2, 11, 27, 54], [3, 12, 28, 56], [10, 14, 31, 62]] },
    { id: 4, name: 'Kevin Donoher', entries: [[2, 22, 30, 60], [1, 12, 40, 57], [5, 17, 37, 66]] },
    { id: 5, name: 'Alex Duff', entries: [[7, 13, 30, 56], [3, 14, 43, 62], [1, 20, 49, 54]] },
    { id: 6, name: 'Garrett Ryan', entries: [[5, 17, 29, 64], [10, 14, 38, 56], [9, 11, 27, 66]] },
    { id: 7, name: 'Kyle Bivenour', entries: [[2, 14, 29, 54], [5, 20, 49, 62], [4, 16, 28, 56]] },
    { id: 8, name: 'Ian Horwich', entries: [[2, 13, 42, 61], [5, 12, 29, 56], [10, 17, 46, 57]] },
    { id: 9, name: 'Nate Heckmann', entries: [[4, 12, 41, 56], [3, 14, 37, 60], [7, 12, 34, 58]] },
    { id: 10, name: 'Ryan Romes', entries: [[5, 17, 31, 60], [1, 13, 27, 59], [9, 11, 30, 62]] },
    { id: 11, name: 'Dan Godshall', entries: [[2, 12, 29, 66], [4, 11, 29, 62], [5, 25, 30, 71]] },
    { id: 12, name: 'Drew Serruto', entries: [[3, 13, 42, 64], [1, 14, 29, 56], [5, 21, 36, 64]] },
    { id: 13, name: 'Matt Weimer', entries: [[3, 11, 29, 55], [2, 14, 33, 68], [1, 17, 34, 56]] },
    { id: 14, name: 'Nick Royer', entries: [[2, 17, 36, 66], [7, 17, 38, 66], [7, 25, 31, 57]] },
    { id: 15, name: 'Kendall Kadish', entries: [[5, 11, 31, 54], [2, 13, 33, 56], [4, 12, 36, 66]] },
    { id: 16, name: 'Lorenzo Washington', entries: [[7, 12, 31, 59], [3, 13, 53, 61], [2, 17, 29, 60]] },
    { id: 17, name: 'Matt Bobson', entries: [[3, 12, 34, 55], [7, 15, 34, 57], [4, 12, 31, 55]] },
    { id: 18, name: 'Ryan Aguiar', entries: [[7, 12, 31, 54], [2, 17, 28, 60], [1, 14, 38, 55]] },
    { id: 19, name: 'Matt Kilianski', entries: [[5, 15, 31, 60], [1, 14, 30, 61], [7, 11, 34, 55]] },
    { id: 20, name: 'Brendan McCausland', entries: [[9, 11, 27, 60], [6, 17, 38, 62], [1, 16, 37, 63]] },
    { id: 21, name: 'Kevin O\'Brien', entries: [[3, 13, 49, 63], [2, 11, 27, 66], [5, 22, 27, 62]] },
    { id: 22, name: 'Cameron Weimer', entries: [[1, 11, 31, 55], [3, 12, 29, 56], [7, 15, 38, 62]] },
    { id: 23, name: 'Cameron Anderson', entries: [[7, 12, 29, 66], [2, 12, 29, 66], [7, 14, 30, 66]] }
];

export default { tourneyTitle, tourneyId, golferData, contestantData };
