const tourneyTitle = '2017 US Open';

const leaderboardUrl = 'http://www.espn.com/golf/leaderboard?tournamentId=3066';

const golferData = [
    { id: 1, firstName: 'Dustin', lastName: 'Johnson', tier: 'A' },
    { id: 2, firstName: 'Jordan', lastName: 'Spieth', tier: 'A' },
    { id: 3, firstName: 'Rory', lastName: 'McIlroy', tier: 'A' },
    { id: 4, firstName: 'Jason', lastName: 'Day', tier: 'A' },
    { id: 5, firstName: 'Jon', lastName: 'Rahm', tier: 'A' },
    { id: 6, firstName: 'Rickie', lastName: 'Fowler', tier: 'A' },
    { id: 7, firstName: 'Justin', lastName: 'Rose', tier: 'A' },
    { id: 8, firstName: 'Sergio', lastName: 'Garcia', tier: 'A' },
    { id: 9, firstName: 'Hideki', lastName: 'Matsuyama', tier: 'A' },
    { id: 10, firstName: 'Henrik', lastName: 'Stenson', tier: 'A' },

    { id: 11, firstName: 'Adam', lastName: 'Scott', tier: 'B' },
    { id: 12, firstName: 'Justin', lastName: 'Thomas', tier: 'B' },
    { id: 13, firstName: 'Brooks', lastName: 'Koepka', tier: 'B' },
    { id: 14, firstName: 'Branden', lastName: 'Grace', tier: 'B' },
    { id: 15, firstName: 'Thomas', lastName: 'Pieters', tier: 'B' },
    { id: 16, firstName: 'Paul', lastName: 'Casey', tier: 'B' },
    { id: 17, firstName: 'Alex', lastName: 'Noren', tier: 'B' },
    { id: 18, firstName: 'Charl', lastName: 'Schwartzel', tier: 'B' },
    { id: 19, firstName: 'Louis', lastName: 'Oosthuizen', tier: 'B' },
    { id: 20, firstName: 'Jason', lastName: 'Dufner', tier: 'B' },
    { id: 21, firstName: 'Matt', lastName: 'Kuchar', tier: 'B' },
    { id: 22, firstName: 'Bubba', lastName: 'Watson', tier: 'B' },
    { id: 23, firstName: 'Daniel', lastName: 'Berger', tier: 'B' },
    { id: 24, firstName: 'Kevin', lastName: 'Chappell', tier: 'B' },
    { id: 25, firstName: 'Kevin', lastName: 'Kisner', tier: 'B' },
    { id: 26, firstName: 'Martin', lastName: 'Kaymer', tier: 'B' },
    { id: 27, firstName: 'Shane', lastName: 'Lowry', tier: 'B' },
    { id: 28, firstName: 'Patrick', lastName: 'Reed', tier: 'B' },
    { id: 29, firstName: 'Billy', lastName: 'Horschel', tier: 'B' },
    { id: 30, firstName: 'Francesco', lastName: 'Molinari', tier: 'B' },
    { id: 31, firstName: 'Marc', lastName: 'Leishman', tier: 'B' },

    { id: 32, firstName: 'Lee', lastName: 'Westwood', tier: 'C' },
    { id: 33, firstName: 'Brandt', lastName: 'Snedeker', tier: 'C' },
    { id: 34, firstName: 'Bud', lastName: 'Cauley', tier: 'C' },
    { id: 35, firstName: 'Byeong Hun', lastName: 'An', tier: 'C' },
    { id: 36, firstName: 'Jimmy', lastName: 'Walker', tier: 'C' },
    { id: 37, firstName: 'Matthew', lastName: 'Fitzpatrick', tier: 'C' },
    { id: 38, firstName: 'Rafael Cabrera', lastName: 'Bello', tier: 'C' },
    { id: 39, firstName: 'Russell', lastName: 'Henley', tier: 'C' },
    { id: 40, firstName: 'Tyrrell', lastName: 'Hatton', tier: 'C' },
    { id: 41, firstName: 'Adam', lastName: 'Hadwin', tier: 'C' },
    { id: 42, firstName: 'Bernd', lastName: 'Wiesberger', tier: 'C' },
    { id: 43, firstName: 'Brendan', lastName: 'Steele', tier: 'C' },
    { id: 44, firstName: 'Emiliano', lastName: 'Grillo', tier: 'C' },
    { id: 45, firstName: 'Gary', lastName: 'Woodland', tier: 'C' },
    { id: 46, firstName: 'J.B.', lastName: 'Holmes', tier: 'C' },
    { id: 47, firstName: 'Si Woo', lastName: 'Kim', tier: 'C' },
    { id: 48, firstName: 'Steve', lastName: 'Stricker', tier: 'C' },
    { id: 49, firstName: 'Tommy', lastName: 'Fleetwood', tier: 'C' },
    { id: 50, firstName: 'Bill', lastName: 'Haas', tier: 'C' },
    { id: 51, firstName: 'Brian', lastName: 'Harman', tier: 'C' },
    { id: 52, firstName: 'Charley', lastName: 'Hoffman', tier: 'C' },
    { id: 53, firstName: 'Graeme', lastName: 'McDowell', tier: 'C' },
    { id: 54, firstName: 'Lucas', lastName: 'Glover', tier: 'C' },
    { id: 55, firstName: 'Ross', lastName: 'Fisher', tier: 'C' },
    { id: 56, firstName: 'Russell', lastName: 'Knox', tier: 'C' },
    { id: 57, firstName: 'Stewart', lastName: 'Cink', tier: 'C' },
    { id: 58, firstName: 'Webb', lastName: 'Simpson', tier: 'C' },
    { id: 59, firstName: 'Zach', lastName: 'Johnson', tier: 'C' },

    { id: 60, firstName: 'Pat', lastName: 'Perez', tier: 'D' },
    { id: 61, firstName: 'Alexander', lastName: 'Levy', tier: 'D' },
    { id: 62, firstName: 'Daniel', lastName: 'Summerhays', tier: 'D' },
    { id: 63, firstName: 'Danny', lastName: 'Willett', tier: 'D' },
    { id: 64, firstName: 'David', lastName: 'Lingmerth', tier: 'D' },
    { id: 65, firstName: 'Hao-tong', lastName: 'Li', tier: 'D' },
    { id: 66, firstName: 'Hideto', lastName: 'Tanihara', tier: 'D' },
    { id: 67, firstName: 'Jhonattan', lastName: 'Vegas', tier: 'D' },
    { id: 68, firstName: 'Keegan', lastName: 'Bradley', tier: 'D' },
    { id: 69, firstName: 'Kevin', lastName: 'Na', tier: 'D' },
    { id: 70, firstName: 'Martin', lastName: 'Laird', tier: 'D' },
    { id: 71, firstName: 'Peter', lastName: 'Uihlein', tier: 'D' },
    { id: 72, firstName: 'Scott', lastName: 'Piercy', tier: 'D' },
    { id: 73, firstName: 'Sean', lastName: 'O\'Hair', tier: 'D' },
    { id: 74, firstName: 'Wesley', lastName: 'Bryan', tier: 'D' },
    { id: 75, firstName: 'William', lastName: 'McGirt', tier: 'D' },
    { id: 76, firstName: 'Andrew', lastName: 'Johnston', tier: 'D' },
    { id: 77, firstName: 'Jamie', lastName: 'Donaldson', tier: 'D' },
    { id: 78, firstName: 'Bryson', lastName: 'DeChambeau', tier: 'D' },
    { id: 79, firstName: 'Cheng Tsung', lastName: 'Pan', tier: 'D' },
    { id: 80, firstName: 'George', lastName: 'Coetzee', tier: 'D' },
    { id: 81, firstName: 'Harris', lastName: 'English', tier: 'D' },
    { id: 82, firstName: 'Jamie', lastName: 'Lovemark', tier: 'D' },
    { id: 83, firstName: 'Jason', lastName: 'Kokrak', tier: 'D' },
    { id: 84, firstName: 'Jeunghun', lastName: 'Wang', tier: 'D' },
    { id: 85, firstName: 'Jim', lastName: 'Furyk', tier: 'D' },
    { id: 86, firstName: 'Paul', lastName: 'Dunne', tier: 'D' },
    { id: 87, firstName: 'Bradley', lastName: 'Dredge', tier: 'D' },
    { id: 88, firstName: 'Brandon', lastName: 'Stone', tier: 'D' },
    { id: 89, firstName: 'Chan', lastName: 'Kim', tier: 'D' },
    { id: 90, firstName: 'Chez', lastName: 'Reavie', tier: 'D' },
    { id: 91, firstName: 'Eddie', lastName: 'Pepperell', tier: 'D' },
    { id: 92, firstName: 'Ernie', lastName: 'Els', tier: 'D' },
    { id: 93, firstName: 'JT', lastName: 'Poston', tier: 'D' },
    { id: 94, firstName: 'Joaquin', lastName: 'Niemann', tier: 'D', isAmateur: true },
    { id: 95, firstName: 'Jordan', lastName: 'Niebrugge', tier: 'D' },
    { id: 96, firstName: 'Maverick', lastName: 'McNealy', tier: 'D', isAmateur: true },
    { id: 97, firstName: 'Richie', lastName: 'Ramsay', tier: 'D' },
    { id: 98, firstName: 'Roberto', lastName: 'Castro', tier: 'D' },
    { id: 99, firstName: 'Ted Potter', lastName: 'Jr.', tier: 'D' },
    { id: 100, firstName: 'Yuta', lastName: 'Ikeda', tier: 'D' },
    { id: 101, firstName: 'Aaron', lastName: 'Rai', tier: 'D' },
    { id: 102, firstName: 'Angel', lastName: 'Cabrera', tier: 'D' },
    { id: 103, firstName: 'Jonathan', lastName: 'Randolph', tier: 'D' },
    { id: 104, firstName: 'Meen Whee', lastName: 'Kim', tier: 'D' },
    { id: 105, firstName: 'Kyle', lastName: 'Thompson', tier: 'D' },
    { id: 106, firstName: 'Matt', lastName: 'Wallace', tier: 'D' },
    { id: 107, firstName: 'Satoshi', lastName: 'Kodaira', tier: 'D' },
    { id: 108, firstName: 'Shugo', lastName: 'Imahira', tier: 'D' },
    { id: 109, firstName: 'Thomas', lastName: 'Aiken', tier: 'D' },
    { id: 110, firstName: 'Stephan', lastName: 'Jaeger', tier: 'D' },
    { id: 111, firstName: 'Andres', lastName: 'Romero', tier: 'D' },
    { id: 112, firstName: 'Brad', lastName: 'Dalke', tier: 'D' },
    { id: 113, firstName: 'Brian', lastName: 'Stuard', tier: 'D' },
    { id: 114, firstName: 'Corey', lastName: 'Conners', tier: 'D' },
    { id: 115, firstName: 'Gene', lastName: 'Sauers', tier: 'D' },
    { id: 116, firstName: 'Jack', lastName: 'Maguire', tier: 'D' },
    { id: 117, firstName: 'Michael', lastName: 'Putnam', tier: 'D' },
    { id: 118, firstName: 'Oliver', lastName: 'Bekker', tier: 'D' },
    { id: 119, firstName: 'Sam', lastName: 'Ryder', tier: 'D' },
    { id: 120, firstName: 'Scottie', lastName: 'Scheffler', tier: 'D', isAmateur: true },
    { id: 121, firstName: 'Talor', lastName: 'Gooch', tier: 'D' },
    { id: 122, firstName: 'Wade', lastName: 'Ormsby', tier: 'D' },
    { id: 123, firstName: 'Xander', lastName: 'Schauffele', tier: 'D' },
    { id: 124, firstName: 'Yusaku', lastName: 'Miyazato', tier: 'D' },
    { id: 125, firstName: 'Daniel', lastName: 'Chopra', tier: 'D' },
    { id: 126, firstName: 'Joel', lastName: 'Stalter', tier: 'D' },
    { id: 127, firstName: 'Ben', lastName: 'Kohles', tier: 'D' },
    { id: 128, firstName: 'Brice', lastName: 'Garnett', tier: 'D' },
    { id: 129, firstName: 'Derek', lastName: 'Barron', tier: 'D' },
    { id: 130, firstName: 'John', lastName: 'Oda', tier: 'D' },
    { id: 131, firstName: 'Ryan', lastName: 'Brehm', tier: 'D' },
    { id: 132, firstName: 'Scott', lastName: 'Gregory', tier: 'D', isAmateur: true },
    { id: 133, firstName: 'Stewart', lastName: 'Hagestad', tier: 'D', isAmateur: true },
    { id: 134, firstName: 'Troy', lastName: 'Merritt', tier: 'D' },
    { id: 135, firstName: 'Andy', lastName: 'Pope', tier: 'D' },
    { id: 136, firstName: 'Trey', lastName: 'Mullinax', tier: 'D' },
    { id: 137, firstName: 'Alex', lastName: 'Smalley', tier: 'D', isAmateur: true },
    { id: 138, firstName: 'Chris', lastName: 'Crawford', tier: 'D', isAmateur: true },
    { id: 139, firstName: 'Daniel', lastName: 'Miernicki', tier: 'D' },
    { id: 140, firstName: 'Garrett', lastName: 'Osborn', tier: 'D' },
    { id: 141, firstName: 'Sahith', lastName: 'Theegala', tier: 'D', isAmateur: true },
    { id: 142, firstName: 'Scott', lastName: 'Harvey', tier: 'D', isAmateur: true },
    { id: 143, firstName: 'Matt', lastName: 'Campbell', tier: 'D' },
    { id: 144, firstName: 'Tyson', lastName: 'Alexander', tier: 'D' },
    { id: 145, firstName: 'Walker', lastName: 'Lee', tier: 'D', isAmateur: true },
    { id: 146, firstName: 'Cameron', lastName: 'Champ', tier: 'D', isAmateur: true },
    { id: 147, firstName: 'Kevin', lastName: 'Dougherty', tier: 'D' },
    { id: 148, firstName: 'Mason', lastName: 'Andersen', tier: 'D', isAmateur: true },
    { id: 149, firstName: 'Max', lastName: 'Greyserman', tier: 'D' },
    { id: 150, firstName: 'Nick', lastName: 'Flanagan', tier: 'D' },
    { id: 151, firstName: 'Roman', lastName: 'Robledo', tier: 'D' }
];

const contestantData = [
    { name: 'Adam Weiss', entries: [[1, 11, 39, 95], [2, 15, 43, 95], [6, 13, 34, 73]] },
    { name: 'Cameron Weimer', entries: [[2, 20, 35, 82], [1, 15, 34, 95], [6, 12, 33, 75]] },
    { name: 'Drew Serruto', entries: [[1, 12, 46, 68], [6, 11, 32, 62], [3, 20, 50, 69]] },
    { name: 'Jon Frantz', entries: [[2, 21, 33, 63], [6, 20, 32, 68], [1, 31, 47, 69]] },
    { name: 'Kevin Donoher', entries: [[1, 11, 36, 60], [5, 16, 43, 61], [6, 19, 50, 71]] },
    { name: 'Kyle Bivenour', entries: [[2, 20, 32, 68], [1, 20, 58, 68], [6, 11, 33, 69]] },
    { name: 'Matt Kilianski', entries: [[3, 12, 40, 64], [1, 27, 33, 68], [6, 27, 48, 62]] },
    { name: 'Matt Weimer', entries: [[2, 12, 32, 95], [6, 13, 40, 62], [1, 20, 33, 75]] },
    { name: 'Nate Heckmann', entries: [[4, 27, 50, 75], [6, 12, 47, 69], [2, 14, 33, 69]] },
    { name: 'Neil Thompson', entries: [[1, 13, 46, 71], [2, 12, 34, 71], [3, 17, 34, 71]] },
    { name: 'Ryan Boudouris', entries: [[4, 11, 48, 60], [3, 13, 38, 85], [1, 15, 32, 62]] },
    { name: 'Nick Royer', entries: [[1, 11, 37, 62], [1, 15, 43, 74], [7, 15, 33, 62]] },
    { name: 'Ryan Romes', entries: [[4, 25, 39, 62], [6, 15, 41, 60], [7, 18, 33, 75]] },
    { name: 'Sean Buckle', entries: [[1, 12, 33, 67], [3, 11, 36, 68], [6, 12, 45, 75]] }
];

export { tourneyTitle, leaderboardUrl, golferData, contestantData };
