const tourneyTitle = '2017 Memorial';

const tourneyId = '2706';

const golferData = [
    { id: 1, name: 'Dustin Johnson', espnId: '3448', tier: 'A' },
    { id: 2, name: 'Jon Rahm', espnId: '9780', tier: 'A' },
    { id: 3, name: 'Jordan Spieth', espnId: '5467', tier: 'A' },
    { id: 4, name: 'Jason Day', espnId: '1680', tier: 'A' },
    { id: 5, name: 'Hideki Matsuyama', espnId: '5860', tier: 'A' },
    { id: 6, name: 'Adam Scott', espnId: '388', tier: 'A' },
    { id: 7, name: 'Rickie Fowler', espnId: '3702', tier: 'A' },
    { id: 8, name: 'Matt Kuchar', espnId: '257', tier: 'A' },
    { id: 9, name: 'Brooks Koepka', espnId: '6798', tier: 'A' },
    { id: 10, name: 'Justin Thomas', espnId: '4848', tier: 'A' },

    { id: 11, name: 'Patrick Reed', espnId: '5579', tier: 'B' },
    { id: 12, name: 'Tony Finau', espnId: '2230', tier: 'B' },
    { id: 13, name: 'Kevin Kisner', espnId: '2552', tier: 'B' },
    { id: 14, name: 'Patrick Cantlay', espnId: '6007', tier: 'B' },
    { id: 15, name: 'Kevin Chappell', espnId: '3857', tier: 'B' },
    { id: 16, name: 'Byeong Hun An', espnId: '5285', tier: 'B' },
    { id: 17, name: 'Emiliano Grillo', espnId: '5882', tier: 'B' },
    { id: 18, name: 'Phil Mickelson', espnId: '308', tier: 'B' },
    { id: 19, name: 'Billy Horschel', espnId: '1651', tier: 'B' },
    { id: 20, name: 'Bud Cauley', espnId: '5338', tier: 'B' },
    { id: 21, name: 'Jason Dufner', espnId: '110', tier: 'B' },
    { id: 22, name: 'Marc Leishman', espnId: '3351', tier: 'B' },
    { id: 23, name: 'Webb Simpson', espnId: '1614', tier: 'B' },
    { id: 24, name: 'Charl Schwartzel', espnId: '1097', tier: 'B' },
    { id: 25, name: 'Bill Haas', espnId: '774', tier: 'B' },
    { id: 26, name: 'Brendan Steele', espnId: '3596', tier: 'B' },
    { id: 27, name: 'Keegan Bradley', espnId: '4513', tier: 'B' },
    { id: 28, name: 'Kevin Tway', espnId: '3793', tier: 'B' },
    { id: 29, name: 'Kyle Stanley', espnId: '1778', tier: 'B' },
    { id: 30, name: 'Shane Lowry', espnId: '4587', tier: 'B' },
    { id: 31, name: 'Steve Stricker', espnId: '412', tier: 'B' },
    { id: 32, name: 'William McGirt', espnId: '3532', tier: 'B' },

    { id: 33, name: 'Adam Hadwin', espnId: '5548', tier: 'C' },
    { id: 34, name: 'Danny Lee', espnId: '3950', tier: 'C' },
    { id: 35, name: 'Gary Woodland', espnId: '3550', tier: 'C' },
    { id: 36, name: 'J.B. Holmes', espnId: '1067', tier: 'C' },
    { id: 37, name: 'Pat Perez', espnId: '707', tier: 'C' },
    { id: 38, name: 'Rafael Cabrera Bello', espnId: '4321', tier: 'C' },
    { id: 39, name: 'Ryan Moore', espnId: '809', tier: 'C' },
    { id: 40, name: 'Scott Piercy', espnId: '1037', tier: 'C' },
    { id: 41, name: 'Sean O\'Hair', espnId: '1359', tier: 'C' },
    { id: 42, name: 'Tommy Fleetwood', espnId: '5539', tier: 'C' },
    { id: 43, name: 'Brian Harman', espnId: '1225', tier: 'C' },
    { id: 44, name: 'Bubba Watson', espnId: '780', tier: 'C' },
    { id: 45, name: 'Charley Hoffman', espnId: '205', tier: 'C' },
    { id: 46, name: 'David Lingmerth', espnId: '5574', tier: 'C' },
    { id: 47, name: 'Ollie Schniederjans', espnId: '9568', tier: 'C' },
    { id: 48, name: 'Ross Fisher', espnId: '3462', tier: 'C' },
    { id: 49, name: 'Graham DeLaet', espnId: '2127', tier: 'C' },
    { id: 50, name: 'Lucas Glover', espnId: '676', tier: 'C' },
    { id: 51, name: 'Si Woo Kim', espnId: '7081', tier: 'C' },
    { id: 52, name: 'Smylie Kaufman', espnId: '9528', tier: 'C' },
    { id: 53, name: 'Zach Johnson', espnId: '686', tier: 'C' },
    { id: 54, name: 'Cameron Smith', espnId: '9131', tier: 'C' },
    { id: 55, name: 'Chris Kirk', espnId: '3449', tier: 'C' },
    { id: 56, name: 'Morgan Hoffmann', espnId: '4781', tier: 'C' },
    { id: 57, name: 'Nick Taylor', espnId: '3792', tier: 'C' },
    { id: 58, name: 'Peter Uihlein', espnId: '1674', tier: 'C' },
    { id: 59, name: 'Russell Knox', espnId: '4483', tier: 'C' },
    { id: 60, name: 'Scott Brown', espnId: '4591', tier: 'C' },
    { id: 61, name: 'Stewart Cink', espnId: '78', tier: 'C' },
    { id: 62, name: 'Sung-hoon Kang', espnId: '4449', tier: 'C' },
    { id: 63, name: 'Jim Furyk', espnId: '153', tier: 'C' },
    { id: 64, name: 'Kevin Streelman', espnId: '1077', tier: 'C' },
    { id: 65, name: 'Soren Kjeldsen', espnId: '547', tier: 'C' },

    { id: 66, name: 'Ben Martin', espnId: '4638', tier: 'D' },
    { id: 67, name: 'Hudson Swafford', espnId: '5504', tier: 'D' },
    { id: 68, name: 'James Hahn', espnId: '5025', tier: 'D' },
    { id: 69, name: 'Jamie Lovemark', espnId: '1676', tier: 'D' },
    { id: 70, name: 'Jason Kokrak', espnId: '3317', tier: 'D' },
    { id: 71, name: 'Jonas Blixt', espnId: '3856', tier: 'D' },
    { id: 72, name: 'Martin Laird', espnId: '2571', tier: 'D' },
    { id: 73, name: 'Patrick Rodgers', espnId: '6825', tier: 'D' },
    { id: 74, name: 'Vaughn Taylor', espnId: '1185', tier: 'D' },
    { id: 75, name: 'Aaron Baddeley', espnId: '16', tier: 'D' },
    { id: 76, name: 'Billy Hurley III', espnId: '1612', tier: 'D' },
    { id: 77, name: 'Daniel Summerhays', espnId: '3452', tier: 'D' },
    { id: 78, name: 'Jim Herman', espnId: '3598', tier: 'D' },
    { id: 79, name: 'Kelly Kraft', espnId: '6689', tier: 'D' },
    { id: 80, name: 'Kyle Reifers', espnId: '1734', tier: 'D' },
    { id: 81, name: 'Luke Donald', espnId: '601', tier: 'D' },
    { id: 82, name: 'Luke List', espnId: '1059', tier: 'D' },
    { id: 83, name: 'Michael Kim', espnId: '8974', tier: 'D' },
    { id: 84, name: 'Ryan Ruffels', espnId: '10096', tier: 'D' },
    { id: 85, name: 'J.J. Spaun', espnId: '10166', tier: 'D' },
    { id: 86, name: 'Brian Stuard', espnId: '3599', tier: 'D' },
    { id: 87, name: 'David Hearn', espnId: '928', tier: 'D' },
    { id: 88, name: 'Harold Varner, III', espnId: '6991', tier: 'D' },
    { id: 89, name: 'Padraig Harrington', espnId: '186', tier: 'D' },
    { id: 90, name: 'Sam Saunders', espnId: '1613', tier: 'D' },
    { id: 91, name: 'Zac Blair', espnId: '9040', tier: 'D' },
    { id: 92, name: 'Anirban Lahiri', espnId: '4989', tier: 'D' },
    { id: 93, name: 'Grayson Murray', espnId: '5462', tier: 'D' },
    { id: 94, name: 'Mackenzie Hughes', espnId: '6931', tier: 'D' },
    { id: 95, name: 'Ricky Barnes', espnId: '801', tier: 'D' },
    { id: 96, name: 'Vijay Singh', espnId: '392', tier: 'D' },
    { id: 97, name: 'Curtis Luck', espnId: '10910', tier: 'D' },
    { id: 98, name: 'Patton Kizzire', espnId: '3980', tier: 'D' },
    { id: 99, name: 'Alex Cejka', espnId: '512', tier: 'D' },
    { id: 100, name: 'C.T. Pan', espnId: '6017', tier: 'D' },
    { id: 101, name: 'D.A. Points', espnId: '1196', tier: 'D' },
    { id: 102, name: 'Fabian Gomez', espnId: '3375', tier: 'D' },
    { id: 103, name: 'Hunter Mahan', espnId: '957', tier: 'D' },
    { id: 104, name: 'Johnson Wagner', espnId: '1265', tier: 'D' },
    { id: 105, name: 'K.J. Choi', espnId: '77', tier: 'D' },
    { id: 106, name: 'Retief Goosen', espnId: '167', tier: 'D' },
    { id: 107, name: 'Roberto Castro', espnId: '3740', tier: 'D' },
    { id: 108, name: 'Rod Pampling', espnId: '335', tier: 'D' },
    { id: 109, name: 'Ryan Armour', espnId: '1750', tier: 'D' },
    { id: 110, name: 'Ryo Ishikawa', espnId: '4047', tier: 'D' },
    { id: 111, name: 'Yuta Ikeda', espnId: '4712', tier: 'D' },
    { id: 112, name: 'Brendon de Jonge', espnId: '1758', tier: 'D' },
    { id: 113, name: 'Brett Coletta', espnId: '10905', tier: 'D' },
    { id: 114, name: 'Carl Pettersson', espnId: '856', tier: 'D' },
    { id: 115, name: 'Greg Chalmers', espnId: '74', tier: 'D' },
    { id: 116, name: 'Matthew Griffin', espnId: '4219', tier: 'D' },
    { id: 117, name: 'Scott Gregory', espnId: '10629', tier: 'D' },
    { id: 118, name: 'Matt Every', espnId: '1411', tier: 'D' },
    { id: 119, name: 'Steven Bowditch', espnId: '1112', tier: 'D' }
];

const contestantData = [
    { id: 1, name: 'Kevin O\'Brien', entries: [[1, 18, 36, 77], [4, 27, 44, 89], [3, 19, 53, 105]] },
    { id: 2, name: 'Matt Kilianski', entries: [[1, 18, 44, 71], [1, 26, 53, 73], [4, 15, 36, 77]] },
    { id: 3, name: 'Matt Weimer', entries: [[8, 32, 51, 81], [4, 32, 63, 66], [7, 11, 33, 67]] },
    { id: 4, name: 'Nate Heckmann', entries: [[1, 12, 35, 77], [2, 16, 33, 80], [8, 12, 33, 67]] },
    { id: 5, name: 'Ryan Boudouris', entries: [[8, 13, 35, 67], [1, 12, 39, 87], [4, 12, 37, 107]] }
];

export default { tourneyTitle, tourneyId, golferData, contestantData };
